# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CGIXo7lnCWOX4L9gVnQk8x8aD1sVJSS3
"""



# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive

import os
if not os.path.isdir("yolov7_project"):
  os.makedirs("yolov7_project")

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov7_project

"""# **Cloning the YOLOv-7 Model from Github**"""

!git clone https://github.com/WongKinYiu/yolov7.git

# Commented out IPython magic to ensure Python compatibility.
# %cd  yolov7

!pip install -r requirements.txt

#Download pretrained weights
!wget "https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt"

"""# **Training the Model**"""

# run this cell to begin training

!python train.py --batch 16 --epochs 50 --cfg /content/drive/MyDrive/yolov7_project/yolov7/cfg/training/custom.yaml --data /content/drive/MyDrive/yolov7_project/yolov7/data/custom_data.yaml --weights /content/drive/MyDrive/yolov7_project/yolov7/yolov7.pt --device 0

"""# **Testing the Model**"""

!python detect.py --source /content/drive/MyDrive/yolov7_project/yolov7/Minor_Project/images/test/augmented_bc_cocklebur_007.jpg --weights runs/train/exp4/weights/best.pt